const ranges=[
[0x1800,['BIRGA','ELLIPSIS','COMMA','FULL STOP','COLON','FOUR DOTS','TODO SOFT HYPHEN','SIBE SYLLABLE BOUNDARY MARKER','MANCHU COMMA','MANCHU FULL STOP','NIRUGU'],'punctuation'],
[0x180B,['FREE VARIATION SELECTOR ONE','FREE VARIATION SELECTOR TWO','FREE VARIATION SELECTOR THREE','VOWEL SEPARATOR','FREE VARIATION SELECTOR FOUR'],'control'],
[0x1810,['DIGIT ZERO','DIGIT ONE','DIGIT TWO','DIGIT THREE','DIGIT FOUR','DIGIT FIVE','DIGIT SIX','DIGIT SEVEN','DIGIT EIGHT','DIGIT NINE'],'digit'],
[0x1820,['LETTER A','LETTER E','LETTER I','LETTER O','LETTER U','LETTER OE','LETTER UE','LETTER EE','LETTER NA','LETTER ANG','LETTER BA','LETTER PA','LETTER QA','LETTER GA','LETTER MA','LETTER LA','LETTER SA','LETTER SHA','LETTER TA','LETTER DA','LETTER CHA','LETTER JA','LETTER YA','LETTER RA','LETTER WA','LETTER FA','LETTER KA','LETTER KHA','LETTER TSA','LETTER ZA','LETTER HAA','LETTER ZRA','LETTER LHA','LETTER ZHI','LETTER CHI'],'letter'],
[0x1843,['LETTER TODO LONG VOWEL SIGN','LETTER TODO E','LETTER TODO I','LETTER TODO O','LETTER TODO U','LETTER TODO OE','LETTER TODO UE','LETTER UE','LETTER TODO ANG','LETTER TODO BA','LETTER TODO PA','LETTER TODO QA','LETTER TODO GA','LETTER TODO MA','LETTER TODO TA','LETTER TODO DA','LETTER TODO CHA','LETTER TODO JA','LETTER TODO TSA','LETTER TODO YA','LETTER TODO WA','LETTER TODO KA','LETTER TODO GAA','LETTER TODO HAA','LETTER TODO JIA','LETTER TODO NIA','LETTER TODO DZA'],'todo'],
[0x185D,['LETTER SIBE E','LETTER SIBE I','LETTER SIBE IY','LETTER SIBE UE','LETTER SIBE U','LETTER SIBE ANG','LETTER SIBE KA','LETTER SIBE GA','LETTER SIBE HA','LETTER SIBE PA','LETTER SIBE SHA','LETTER SIBE TA','LETTER SIBE DA','LETTER SIBE JA','LETTER SIBE FA','LETTER SIBE GAA','LETTER SIBE HAA','LETTER SIBE TSA','LETTER SIBE ZA','LETTER SIBE RAA','LETTER SIBE CHA','LETTER SIBE ZHA'],'sibe'],
[0x1873,['LETTER MANCHU I','LETTER MANCHU KA','LETTER MANCHU RA','LETTER MANCHU FA','LETTER MANCHU ZHA'],'manchu'],
[0x1880,['LETTER ALI GALI ANUSVARA ONE','LETTER ALI GALI VISARGA ONE','LETTER ALI GALI DAMARU','LETTER ALI GALI UBADAMA','LETTER ALI GALI INVERTED UBADAMA','LETTER ALI GALI BALUDA','LETTER ALI GALI THREE BALUDA','LETTER ALI GALI A','LETTER ALI GALI I','LETTER ALI GALI KA','LETTER ALI GALI NGA','LETTER ALI GALI CA','LETTER ALI GALI TTA','LETTER ALI GALI TTHA','LETTER ALI GALI DDA','LETTER ALI GALI NNA','LETTER ALI GALI TA','LETTER ALI GALI DA','LETTER ALI GALI PA','LETTER ALI GALI PHA','LETTER ALI GALI SSA','LETTER ALI GALI ZHA','LETTER ALI GALI ZA','LETTER ALI GALI AH','LETTER TODO ALI GALI TA','LETTER TODO ALI GALI ZHA','LETTER MANCHU ALI GALI GHA','LETTER MANCHU ALI GALI NGA','LETTER MANCHU ALI GALI CA','LETTER MANCHU ALI GALI JHA','LETTER MANCHU ALI GALI TTA','LETTER MANCHU ALI GALI DDHA','LETTER MANCHU ALI GALI TA','LETTER MANCHU ALI GALI DHA','LETTER MANCHU ALI GALI SSA','LETTER MANCHU ALI GALI CYA','LETTER MANCHU ALI GALI ZHA','LETTER MANCHU ALI GALI ZA','LETTER ALI GALI HALF U','LETTER ALI GALI HALF YA','LETTER MANCHU ALI GALI BHA','LETTER ALI GALI DAGALGA','LETTER MANCHU ALI GALI LHA'],'manchu']
];
const chars=[];for(let cp=0x1800;cp<=0x18AF;cp++){chars.push({cp,hex:'U+'+cp.toString(16).toUpperCase().padStart(4,'0'),char:'',name:'UNASSIGNED',category:'unassigned',assigned:false});}
ranges.forEach(([start,names,cat])=>names.forEach((n,i)=>{const cp=start+i;const item=chars.find(x=>x.cp===cp);if(item){item.char=String.fromCodePoint(cp);item.name='MONGOLIAN '+n;item.category=cat;item.assigned=true;}}));
const labels={punctuation:'标点',control:'控制符 / 变体选择器',digit:'数字',letter:'蒙古字母',todo:'Todo 字母',sibe:'Sibe 字母',manchu:'Manchu / Ali Gali',unassigned:'未分配'};
const $=id=>document.getElementById(id);const rows=$('charRows'),q=$('charSearch'),visible=$('visibleCount'),assigned=$('assignedCount'),reserved=$('reservedCount'),preview=$('selectedPreview'),info=$('selectedInfo');let filter='all';let focusHex=null;let selected=null;
function ent(cp){return '&#x'+cp.toString(16).toUpperCase()+';'}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalizeHex(value){if(!value)return null;const raw=String(value).trim().toUpperCase().replace(/^U\+/,'');if(!/^[0-9A-F]{4,6}$/.test(raw))return null;return 'U+'+raw.padStart(4,'0');}
function analyzeUrl(x){const text=x.assigned?x.char:x.hex;return 'tools.html?text='+encodeURIComponent(text)+'&cp='+encodeURIComponent(x.hex);}
function flashCopied(el){if(!el)return;const old=el.textContent;el.textContent='已复制';el.classList.add('copied');setTimeout(()=>{el.textContent=old;el.classList.remove('copied');},1200);}
function copyText(value,el){navigator.clipboard?.writeText(value).then(()=>flashCopied(el)).catch(()=>{flashCopied(el);});}
function showChar(x){if(!x.assigned)return '<span class="invisible-tag">未分配</span>';if(x.category==='control')return '<span class="invisible-tag">'+x.hex+'</span>';return '<span class="char-cell">'+esc(x.char)+'</span>';}
function match(x,t){if(!t)return true;const u=t.toUpperCase().replace(/^U\+/,'');return x.hex.includes(t.toUpperCase())||x.hex.replace('U+','').includes(u)||x.name.toUpperCase().includes(t.toUpperCase())||labels[x.category].includes(t)||x.char===t;}
function render(){const t=q.value.trim();const list=chars.filter(x=>(filter==='all'||x.category===filter)&&match(x,t));rows.innerHTML=list.map(x=>`<tr data-cp="${x.cp}" data-hex="${x.hex}" class="${focusHex===x.hex?'focused-row':''}"><td><code>${x.hex}</code></td><td class="cp-char">${showChar(x)}</td><td>${esc(x.name)}</td><td><span class="invisible-tag">${labels[x.category]}</span></td><td><code>${ent(x.cp)}</code></td><td><button class="tool-button ghost mini" data-copy="${x.hex}">复制码位</button> <a class="tool-button mini" href="${analyzeUrl(x)}">带入工具</a></td></tr>`).join('');visible.textContent=list.length;assigned.textContent=chars.filter(x=>x.assigned).length;reserved.textContent=chars.filter(x=>!x.assigned).length;}
function select(x){selected=x;const previewBody=x.assigned?`<div class="char-preview-char">${esc(x.char)}</div>`:'<div class="char-preview-char muted">未分配</div>';preview.innerHTML=`${previewBody}<div class="tool-actions char-detail-actions"><button class="tool-button mini" data-detail-action="copy-char" ${x.assigned?'':'disabled'}>复制字符</button><button class="tool-button ghost mini" data-detail-action="copy-code">复制码位</button><a class="tool-button mini" href="${analyzeUrl(x)}">带入工具</a></div>`;info.textContent=[`Code point: ${x.hex}`,`Decimal: ${x.cp}`,`Character: ${x.assigned?x.char:'(unassigned)'}`,`Name: ${x.name}`,`Category: ${labels[x.category]}`,`HTML entity: ${ent(x.cp)}`].join('\n');}
function applyFocusFromQuery(){const params=new URLSearchParams(window.location.search);const target=normalizeHex(params.get('focus'));if(!target)return;const item=chars.find(x=>x.hex===target);if(!item)return;focusHex=target;filter='all';q.value=target;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.add('ghost'));const allBtn=document.querySelector('[data-filter="all"]');if(allBtn)allBtn.classList.remove('ghost');render();select(item);setTimeout(()=>{const row=rows.querySelector(`tr[data-hex="${target}"]`);if(row){row.scrollIntoView({behavior:'smooth',block:'center'});row.classList.add('focused-row-pulse');}},120);}
q.addEventListener('input',()=>{focusHex=null;render();});document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{focusHex=null;filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.add('ghost'));b.classList.remove('ghost');render();}));rows.addEventListener('click',e=>{const copy=e.target.closest('[data-copy]');if(copy){copyText(copy.dataset.copy,copy);return;}const tr=e.target.closest('tr[data-cp]');if(tr)select(chars.find(x=>x.cp===Number(tr.dataset.cp)));});
preview.addEventListener('click',e=>{const action=e.target.closest('[data-detail-action]');if(!action||!selected)return;if(action.dataset.detailAction==='copy-char'&&selected.assigned)copyText(selected.char,action);if(action.dataset.detailAction==='copy-code')copyText(selected.hex,action);});
render();select(chars.find(x=>x.cp===0x1820));applyFocusFromQuery();
